spring:
  application:
    name: lets-play
  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017/lets-play}
  data:
    mongodb:
      auto-index-creation: true

jwt:
  secret: ${JWT_SECRET:SFsVh50wQRIIqqgzWEYteYwGz1KIyUCKQRJulJgC2kU=}
  expiration-ms: 3600000

server:
  port: 8080

admin:
  seed:
    email: ${ADMIN_EMAIL:admin@gmail.com}
    password: ${ADMIN_PASSWORD:admin123456789}