spring:
  application:
    name: lets-play
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/lets-play}
      auto-index-creation: true

jwt:
  secret: ${JWT_SECRET:SFsVh50wQRIIqqgzWEYteYwGz1KIyUCKQRJulJgC2kU=}
  expiration-ms: 3600000

server:
  port: 8080
